# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:38
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=256, verbose_name='Название поста')),
                ('post_text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('post_date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('post_date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата последней модификации')),
                ('post_is_released', models.BooleanField(default=True, verbose_name='Статус публичности')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
